# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('project_group', models.CharField(max_length=50, verbose_name='项目组')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('environment', models.CharField(max_length=50, verbose_name='所属环境')),
            ],
        ),
    ]
