# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='port',
            field=models.IntegerField(default=8080, verbose_name='服务监听端口'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='service_status',
            field=models.BooleanField(default=0, verbose_name='服务状态'),
        ),
    ]
