# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170328_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='service_start_path',
            field=models.CharField(default='/home/tomcat/tomcat-7.0.54/bin/start.sh', max_length=80, verbose_name='服务启动脚本'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='service_stop_path',
            field=models.CharField(default='/home/tomcat/tomcat7.0.54/bin/stop.sh', max_length=80, verbose_name='服务停止脚本'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='svn_path',
            field=models.CharField(default='', max_length=100, verbose_name='代码svn存放路径'),
        ),
    ]
